<a href="https://colab.research.google.com/github/shivansh2310/Finance-Stuff/blob/main/Basic_Portfolio_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
!pip install yfinance

import numpy as np
import pandas as pd
import datetime
import yfinance as yf
from tqdm.notebook import tqdm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [31]:
stocks = ['REDINGTON.NS', 'INFY.NS', 'TCS.NS', 'ITC.NS', 'HDFCBANK.NS']
start = datetime.datetime(2010,1,1)
end = datetime.datetime(2022,12,31)
numPortfolios = 50000
risk_free_return = 0.061

In [32]:
pct_returns = yf.download(stocks,start = start, end = end)['Adj Close'].pct_change()

[*********************100%***********************]  5 of 5 completed


In [33]:
portfolio_weights = []
portfolio_returns = []
portfolio_risk = []
portfolio_sharpe_ratio = []


In [34]:
np.random.seed(0)

for portfolio in tqdm(range(numPortfolios)):

  #Randomize weights for the portfolio
  weights = np.random.random_sample(len(stocks))
  weights = weights/np.sum(weights)
  portfolio_weights.append(weights)
  print(weights)

  #Annual portfolio returns according to above weights
  annual_return = np.sum(pct_returns.mean() * weights) * 252
  portfolio_returns.append(annual_return)

  #Portfolio Risk Calcualtion
  cov_matrix = pct_returns.cov() * 252
  portfolio_variance = np.dot(weights.T, np.dot(cov_matrix,weights))
  portfolio_std_dev = np.sqrt(portfolio_variance)
  portfolio_risk.append(portfolio_std_dev)

  #Portfolio sharpe ratio calculation
  Sharpe_ration = (annual_return - risk_free_return)/portfolio_std_dev
  portfolio_sharpe_ratio.append(Sharpe_ration)



  0%|          | 0/50000 [00:00<?, ?it/s]

Streaming output truncated to the last 5000 lines.
[0.37966703 0.00136688 0.02754532 0.31756389 0.27385689]
[0.37706281 0.09347876 0.18362498 0.04411646 0.30171698]
[0.05294044 0.54299367 0.18256086 0.06436749 0.15713753]
[0.28518001 0.26594996 0.02557566 0.27592701 0.14736736]
[0.38203467 0.54398473 0.02713629 0.03226242 0.01458188]
[0.09860021 0.22748266 0.02473558 0.31181209 0.33736945]
[0.13126809 0.11580038 0.19926002 0.15518925 0.39848226]
[0.28950347 0.23898163 0.18976646 0.05084879 0.23089965]
[0.1643402  0.09393546 0.34841091 0.1170928  0.27622063]
[0.23327601 0.36020211 0.24811108 0.14635632 0.01205448]
[0.3870022  0.12531912 0.35347704 0.00196985 0.13223179]
[0.0550154  0.08841806 0.05040435 0.46927889 0.3368833 ]
[0.28662053 0.22941739 0.23221108 0.06162998 0.19012102]
[0.26781477 0.02505511 0.1958576  0.29465621 0.21661631]
[0.29399221 0.22030883 0.21048835 0.02042848 0.25478213]
[0.45112538 0.03502872 0.23796227 0.19624946 0.07963416]
[0.02088571 0.12697459 0.1687213  0.3

In [35]:
metrics = [portfolio_returns,portfolio_risk,portfolio_sharpe_ratio,portfolio_weights]
portfolio_df = pd.DataFrame(metrics).T

portfolio_df.columns = ['Return', 'Risk', 'Sharpe Ratio', 'Associated Weights']

In [36]:
portfolio_df

Return      Risk Sharpe Ratio  \
0      0.204071  0.175616     0.814678   
1      0.209274   0.18818     0.787934   
2      0.211761  0.197063     0.765038   
3      0.212917  0.195674     0.776374   
4       0.20881  0.186198      0.79383   
...         ...       ...          ...   
49995   0.17081  0.209214     0.524868   
49996  0.191997  0.175323     0.747176   
49997  0.213522  0.183997     0.828938   
49998   0.21815  0.184196     0.853165   
49999  0.213413  0.191291     0.796757   

                                      Associated Weights  
0      [0.1935642384935766, 0.25224431266711844, 0.21...  
1      [0.19440830746079796, 0.1317098072068841, 0.26...  
2      [0.2743998205285077, 0.18330691095749266, 0.19...  
3      [0.033664878826107324, 0.007811951917646457, 0...  
4      [0.311854579742372, 0.2546664490497017, 0.1470...  
...                                                  ...  
49995  [0.036857898752655244, 0.19177340328262416, 0....  
49996  [0.161206280479566, 0.3401732306017866, 0.2829...  
49997  [0.18681380827214703, 0.10663435851263846, 0.2...  
49998  [0.3924614563368664, 0.12085874097892886, 0.04...  
49999  [0.3607906180441625, 0.07532872443766837, 0.20...  

[50000 rows x 4 columns]

### Minimal Risk Portfolio


In [37]:
min_risk_portfolio = portfolio_df.iloc[portfolio_df.Risk.astype('float64').argmin()].to_frame().T

In [38]:
min_risk_portfolio

Return      Risk Sharpe Ratio  \
17691  0.199955  0.168038     0.826922   

                                      Associated Weights  
17691  [0.2820644757804782, 0.15451390806585863, 0.26...

In [39]:
print('For a minimal Risk Portfolio')
print()
print('STOCK SYMBOL' + '       ' + 'Allocation Percentage')
print('----------------------------------------------')

for stock,per_alloc in zip(stocks,min_risk_portfolio['Associated Weights']. values[0]):
  print()
  print(stock + '-------------' + str(per_alloc *100))


For a minimal Risk Portfolio

STOCK SYMBOL       Allocation Percentage
----------------------------------------------

REDINGTON.NS-------------28.206447578047822

INFY.NS-------------15.451390806585863

TCS.NS-------------26.814387052768176

ITC.NS-------------7.947979228132683

HDFCBANK.NS-------------21.579795334465473


###Maximal Return portfolio

In [40]:
max_return_portfolio = portfolio_df.iloc[portfolio_df.Return.astype('float64').argmax()].to_frame().T

In [41]:
max_return_portfolio

Return      Risk Sharpe Ratio  \
24896  0.246711  0.331295     0.560561   

                                      Associated Weights  
24896  [0.1667138677720768, 0.004043793863419787, 0.0...

In [42]:
print('For a Maximum Return Portfolio')
print()
print('STOCK SYMBOL' + '       ' + 'Allocation Percentage')
print('----------------------------------------------')

for stock,per_alloc in zip(stocks,max_return_portfolio['Associated Weights']. values[0]):
  print()
  print(stock + '-------------' + str(per_alloc *100))

For a Maximum Return Portfolio

STOCK SYMBOL       Allocation Percentage
----------------------------------------------

REDINGTON.NS-------------16.67138677720768

INFY.NS-------------0.4043793863419787

TCS.NS-------------1.3214397503407844

ITC.NS-------------76.80317303175245

HDFCBANK.NS-------------4.799621054357096


### Maximum Sharpe Ratio Portfolio

In [43]:
max_sharpeRatio_portfolio = portfolio_df.iloc[portfolio_df['Sharpe Ratio'].astype('float64').argmax()].to_frame().T

In [44]:
max_sharpeRatio_portfolio

Return      Risk Sharpe Ratio  \
30687  0.217563  0.178275      0.87821   

                                      Associated Weights  
30687  [0.3634030809185228, 0.005624451256477614, 0.1...

In [45]:
print('For a Maximum Sharpe Ratio Portfolio')
print()
print('STOCK SYMBOL' + '       ' + 'Allocation Percentage')
print('----------------------------------------------')

for stock,per_alloc in zip(stocks,max_sharpeRatio_portfolio['Associated Weights']. values[0]):
  print()
  print(stock + '-------------' + str(per_alloc *100))

For a Maximum Sharpe Ratio Portfolio

STOCK SYMBOL       Allocation Percentage
----------------------------------------------

REDINGTON.NS-------------36.34030809185228

INFY.NS-------------0.5624451256477614

TCS.NS-------------10.703925174923896

ITC.NS-------------16.372303832269388

HDFCBANK.NS-------------36.021017775306674
