<a href="https://colab.research.google.com/github/shivansh2310/Finance-Stuff/blob/main/Quiz_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Cholesky decomposition and Correlation matrix

In [1]:
# Import libraries
%matplotlib inline
from math import exp, sqrt

import matplotlib.pyplot as plt
import numpy as np
import yfinance as yf

In [49]:
tickers = ["BA", "C", "JPM"]
df_tickers = yf.download(tickers, start="2020-01-01", end="2020-12-31")["Adj Close"]
df_tickers.head()

[*********************100%%**********************]  3 of 3 completed


Ticker              BA          C         JPM
Date                                         
2020-01-02  331.348572  68.369751  123.533615
2020-01-03  330.791901  67.081985  121.903412
2020-01-06  331.766083  66.871567  121.806465
2020-01-07  335.285156  66.290794  119.735695
2020-01-08  329.410095  66.795815  120.669754

In [50]:
df_tickers_ret = df_tickers / df_tickers.shift(1) - 1
volatility = (
    df_tickers_ret.std()
)  # This is daily volatility, we will later on annualize it!
df_tickers_corr = df_tickers_ret.corr()
print(df_tickers_corr)

Ticker        BA         C       JPM
Ticker                              
BA      1.000000  0.732748  0.709412
C       0.732748  1.000000  0.916919
JPM     0.709412  0.916919  1.000000


In [54]:
# Perform Cholesky decomposition on coefficient matrix
R = np.linalg.cholesky(df_tickers_corr)

# Compute transpose conjugate (only for validation)
RT = R.T.conj()

# Compare the R matrix and check the reconstruction of the original correlation matrix:
# 1. R  matrix from Cholesky decomposition
print("This is the R matrix: ")
print(R)
# 2. Reconstruct coefficient matrix from factorization (only for validation)
print("This is the reconstructed original correlation matrix ")
print(np.dot(R, RT))

This is the R matrix: 
[[1.         0.         0.        ]
 [0.73274843 0.68049963 0.        ]
 [0.70941221 0.58353931 0.39524194]]
This is the reconstructed original correlation matrix 
[[1.         0.73274843 0.70941221]
 [0.73274843 1.         0.91691896]
 [0.70941221 0.91691896 1.        ]]


## Continuous Compounded returns

In [22]:
tickers = ["XOM"]
df_tickers = yf.download(tickers, start="2021-01-01", end="2021-12-31")
df_tickers.head()

[*********************100%%**********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2021-01-04  41.450001  42.250000  41.000000  41.500000  35.737587  27764700
2021-01-05  41.840000  44.799999  41.830002  43.500000  37.459869  44035100
2021-01-06  44.410000  45.099998  43.700001  44.610001  38.415745  36484800
2021-01-07  45.000000  45.570000  44.529999  44.959999  38.717148  29528100
2021-01-08  45.200001  45.820000  44.950001  45.459999  39.147720  28628200

In [37]:
import yfinance as yf
import pandas as pd
import numpy as np

# Define the stock ticker and the date range
ticker = 'AMZN'
start_date = '2021-01-01'
end_date = '2021-12-31'

# Fetch the historical data
data = yf.download(ticker, start=start_date, end=end_date)

# Check if data is not empty
if data.empty:
    print(f"No data found for ticker {ticker} between {start_date} and {end_date}.")
else:
    # Use the Adjusted Close prices
    data['Adjusted Close'] = data['Adj Close']

    # Calculate the daily continuous compounded returns
    data['Log Return'] = np.log(data['Adjusted Close'] / data['Adjusted Close'].shift(1))

    # Drop the first NaN value
    log_returns = data['Log Return'].dropna()

    # Calculate the cumulative log return
    cumulative_log_return = log_returns.sum()

    print(cumulative_log_return * 100)

[*********************100%%**********************]  1 of 1 completed

5.680603354093318


In [85]:
import yfinance as yf
import pandas as pd
import numpy as np

# Define the stock ticker and the date range
ticker = 'AAPL'
start_date = '2021-01-01'
end_date = '2021-07-30'

# Fetch the historical data
data = yf.download(ticker, start=start_date, end=end_date)

# Check if data is not empty
if data.empty:
    print(f"No data found for ticker {ticker} between {start_date} and {end_date}.")
else:
    # Use the Adjusted Close prices
    data['Adjusted Close'] = data['Adj Close']

    # Calculate the daily continuous compounded returns
    data['Log Return'] = np.log(data['Adjusted Close'] / data['Adjusted Close'].shift(1))

    # Drop the first NaN value
    log_returns = data['Log Return'].dropna()

    # Calculate the cumulative log return
    cumulative_log_return = log_returns.sum()

    # Initial investment
    initial_investment = 10000

    # Calculate the value of the investment by the end date

    final_value = initial_investment * (1 + cumulative_log_return)

    print(f"\n Value of a $10,000 investment in Tesla (TSLA) from the first trading day of January 2021 to July 30, 2021: ${final_value:.2f}")


[*********************100%%**********************]  1 of 1 completed


 Value of a $10,000 investment in Tesla (TSLA) from the first trading day of January 2021 to July 30, 2021: $11213.43


## Dicsrete annual compunded return

In [86]:
import yfinance as yf
import pandas as pd

# Define the stock ticker and the date range
ticker = 'AAPL'
start_date = '2021-01-01'
end_date = '2021-07-30'

# Fetch the historical data
data = yf.download(ticker, start=start_date, end=end_date)



# Calculate the daily returns
data['Daily Return'] = data['Adj Close'].pct_change()

# Drop the first NaN value
daily_returns = data['Daily Return'].dropna()

# Calculate the cumulative return
cumulative_return = (1 + daily_returns).prod() - 1

# Initial investment
initial_investment = 10000

# Calculate the value of the investment by the end date
final_value = initial_investment * (1 + cumulative_return)

print(f"Value of a $10,000 investment in Tesla (TSLA) from the first trading day of January 2021 to July 30, 2021: ${final_value:.2f}")


[*********************100%%**********************]  1 of 1 completed

Value of a $10,000 investment in Tesla (TSLA) from the first trading day of January 2021 to July 30, 2021: $11290.12


## Annual return

## investment return

## Daily return

In [8]:
df_tickers['Daily Return'] = df_tickers['Close'].pct_change()

In [9]:
df_tickers['Daily Return'].min()*100

-8.549845855559933

In [45]:
tickers = ["JPM"]
df_jpm = yf.download(tickers, start="2007-01-01", end="2010-12-31")
df_jpm.head()

[*********************100%%**********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2007-01-03  48.000000  48.369999  47.590000  48.070000  30.657495  14244700
2007-01-04  48.049999  48.549999  47.750000  48.189999  30.734026   9471500
2007-01-05  48.169998  48.250000  47.630001  47.790001  30.478937  10760500
2007-01-08  47.570000  48.060001  47.320000  47.950001  30.580976   8239200
2007-01-09  47.900002  48.110001  47.360001  47.750000  30.453405   9276700

## Annual Volatitlity

In [46]:
df_ret = df_jpm['Adj Close'].pct_change()
daily_vol = df_ret.std()
annual_vol = daily_vol * np.sqrt(252)

In [47]:
annual_vol * 100

62.028430864414176

In [90]:
A_ret = 0.325
n_year = 30
Initial_invest = 1000

Total_ret = (1 + A_ret) ** n_year
Final_invest = Initial_invest * Total_ret
print("Your investment will be worth " + str(Final_invest / 10 ** 6 ) + " millions!")

Your investment will be worth 4.63955522129227 millions!


In [16]:
corr = np.array([[0.056, 0.025], [0.025, 0.045]])

R = np.linalg.cholesky(corr)

print(R)



[[0.23664319 0.        ]
 [0.10564428 0.18395458]]


## Correleted random variable

In [39]:
import numpy as np

# Set the random seed for reproducibility
np.random.seed(10)

# Define the correlation matrix
correlation_matrix = np.array([
    [1, 0.679, 0.338],
    [0.679, 1, 0.435],
    [0.338, 0.435, 1]
])

# Perform Cholesky decomposition
L = np.linalg.cholesky(correlation_matrix)

# Generate standard normal random variables
Z = np.random.standard_normal(3)

# Transform to correlated random variables
correlated_random_variables = np.dot(L, Z)

# Print the correlated random variables
print("Correlated Random Variables:", correlated_random_variables)

Correlated Random Variables: [ 1.3315865   1.42926091 -0.73833301]


In [69]:
T = 1 /12
N = 30
dt = T / N

In [88]:
( (-0.25 * 0.44) + (-1.26 * np.sqrt(1 - (-0.25 ** 2))) ) * 0.15

-0.21131674081043447

In [89]:
(14/16) * 100

87.5

In [92]:
0.25 * np.sqrt(1/12)

0.07216878364870322

In [94]:
(44 + 44 + 47 + 31 + 38 + 41 + 41)

286

In [95]:
108 + 286 + 88 + 88 + 110 + 110 + 110

900