<a href="https://colab.research.google.com/github/shivansh2310/Finance-Stuff/blob/main/SM_Test_Codes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from scipy.stats import norm

In [52]:
## EM Algorithm

def mu_value(y_1, y_2, e_1, e_2):
    estimate = ((e_1 * y_1) + (e_2 * y_2)) / (e_1 + e_2)
    return estimate

In [53]:
y_1 = 0.5
y_2 = -0.625
e_1 = 0.55
e_2 = 0.3

In [54]:
mu_value = mu_value(y_1, y_2, e_1, e_2)
print(mu_value)

0.10294117647058824


In [7]:
def sigma_value(y_1, y_2, mu, e_1, e_2):
    nxt_1 = (y_1 - mu)**2
    nxt_2 = (y_2 - mu)**2
    sigma = ((e_1 * nxt_1) + (e_2 * nxt_2)) / (e_1 + e_2)
    return sigma

In [8]:
y_1 = 0.4
y_2 = -0.5
e_1 = 0.45
e_2 = 0.7
mu = -0.15

In [9]:
sigma_value = sigma_value(y_1, y_2, mu, e_1, e_2)
print(sigma_value)

0.19293478260869565


In [10]:
# Kim Smoother

Xi_t_t = np.array([0.1, 0.8, 0.1])
Xi_t1_t = np.array([0.275, 0.45, 0.275])
Xi_t1_T = np.array([0.25, 0.5, 0.25])

p = np.array([
[0.5, 0.25, 0.25],
[0.25, 0.5, 0.25],
[0.25, 0.25, 0.5]
])


division_result = Xi_t1_T / Xi_t1_t

intermediate_result = np.dot(p, division_result)

Xi_t_T = Xi_t_t * intermediate_result

Xi_t_T /= np.sum(Xi_t_T)

print("Smoothed probabilities Xi_t|T:", Xi_t_T)

Smoothed probabilities Xi_t|T: [0.0959596  0.80808081 0.0959596 ]


In [56]:
#Hamilton Filter

# Given values
Xi_t_t_minus_1 = np.array([0.1, 0.9])
y_t = 1.5
mu = np.array([-3, 3])
sigma = np.array([1, 1])
P = np.array([[0.8, 0.2], [0.3, 0.7]])

# Step 1: Compute predicted state probabilities
Xi_t_t_minus_1_pred = np.dot(P.T, Xi_t_t_minus_1)

# Step 2: Compute marginal likelihoods
likelihoods = norm.pdf(y_t, mu, sigma)

# Step 3: Update state probabilities
Xi_t_t = Xi_t_t_minus_1_pred * likelihoods

# Step 4: Normalize the updated probabilities
Xi_t_t /= np.sum(Xi_t_t)

print("Predicted state probabilities Xi_{t|t-1}:", Xi_t_t_minus_1_pred)
print("Marginal likelihoods:", likelihoods)
print("Updated state probabilities Xi_{t|t}:", Xi_t_t)


Predicted state probabilities Xi_{t|t-1}: [0.35 0.65]
Marginal likelihoods: [1.59837411e-05 1.29517596e-01]
Updated state probabilities Xi_{t|t}: [6.64470175e-05 9.99933553e-01]


In [59]:
import numpy as np
from scipy.stats import norm

# Given parameters
Xi_t_t_minus_1 = np.array([0.1, 0.9])
y_t = 1.5
y_t_plus_1 = 2
mu = np.array([-3, 3])
sigma = 1
P = np.array([[0.8, 0.2],
              [0.3, 0.7]])

# Step 1: Calculate likelihoods for y_t
likelihoods_t = norm.pdf(y_t, mu, sigma)

# Step 2: Calculate joint probabilities
joint_probs = likelihoods_t * Xi_t_t_minus_1

# Step 3: Calculate marginal likelihood
marginal_likelihood = np.sum(joint_probs)

# Step 4: Update state probabilities (Xi_t|t)
Xi_t_t = joint_probs / marginal_likelihood

# Step 5: Forecast state probabilities for t+1
Xi_t_plus_1_t = P.T @ Xi_t_t

# Step 6: Calculate likelihoods for y_t+1
likelihoods_t_plus_1 = norm.pdf(y_t_plus_1, mu, sigma)

# Step 7: Calculate likelihood of y_t+1
likelihood_y_t_plus_1 = np.sum(likelihoods_t_plus_1 * Xi_t_plus_1_t)

print(f"Likelihood of y_t+1 = {y_t_plus_1}: {likelihood_y_t_plus_1:.6f}")

# Additional information
print(f"\nUpdated state probabilities (Xi_t|t): {Xi_t_t}")
print(f"Forecasted state probabilities for t+1 (Xi_t+1|t): {Xi_t_plus_1_t}")

Likelihood of y_t+1 = 2: 0.169378

Updated state probabilities (Xi_t|t): [1.37120124e-05 9.99986288e-01]
Forecasted state probabilities for t+1 (Xi_t+1|t): [0.30000686 0.69999314]


In [61]:
import numpy as np
from scipy.stats import norm

# Given parameters
Xi_t_t_minus_1 = np.array([0.1, 0.9])
y_t = 1.5
y_t_plus_1 = 2
mu = np.array([-3, 3])
sigma = 1
P = np.array([[0.8, 0.2],
              [0.3, 0.7]])

# Step 1: Calculate likelihoods for y_t
likelihoods_t = norm.pdf(y_t, mu, sigma)

# Step 2: Calculate joint probabilities
joint_probs = likelihoods_t * Xi_t_t_minus_1

# Step 3: Calculate marginal likelihood
marginal_likelihood = np.sum(joint_probs)

# Step 4: Update state probabilities (Xi_t|t)
Xi_t_t = joint_probs / marginal_likelihood

# Step 5: Forecast state probabilities for t+1
Xi_t_plus_1_t = P.T @ Xi_t_t

# Step 6: Calculate likelihoods for y_t+1
likelihoods_t_plus_1 = norm.pdf(y_t_plus_1, mu, sigma)

# Step 7: Calculate likelihood of y_t+1
likelihood_y_t_plus_1 = np.sum(likelihoods_t_plus_1 * Xi_t_plus_1_t)

print(f"Likelihood of y_t+1 = {y_t_plus_1}: {likelihood_y_t_plus_1:.6f}")

# Additional information
print(f"\nUpdated state probabilities (Xi_t|t): {Xi_t_t}")
print(f"Forecasted state probabilities for t+1 (Xi_t+1|t): {Xi_t_plus_1_t}")


Likelihood of y_t+1 = 2: 0.169378

Updated state probabilities (Xi_t|t): [1.37120124e-05 9.99986288e-01]
Forecasted state probabilities for t+1 (Xi_t+1|t): [0.30000686 0.69999314]


In [26]:
# Tauchen method

# Parameters
rho = 0.9
sigma_e = 0.2
lambda_param = 2
N = 3

# Standard deviation of the stationary distribution
sigma_z = sigma_e / np.sqrt(1 - rho**2)

# Grid points
z = np.linspace(-lambda_param * sigma_z, lambda_param * sigma_z, N)

# Transition matrix
P = np.zeros((N, N))
delta_z = z[1] - z[0]

for i in range(N):
    for j in range(N):
        if j == 0:
            P[i, j] = norm.cdf((z[j] - rho * z[i] + delta_z / 2) / sigma_e)
        elif j == N-1:
            P[i, j] = 1 - norm.cdf((z[j] - rho * z[i] - delta_z / 2) / sigma_e)
        else:
            P[i, j] = norm.cdf((z[j] - rho * z[i] + delta_z / 2) / sigma_e) - norm.cdf((z[j] - rho * z[i] - delta_z / 2) / sigma_e)

print("Grid points:", z)
print("Transition matrix:\n", P)


Grid points: [-0.91766294  0.          0.91766294]
Transition matrix:
 [[9.66771290e-01 3.32287099e-02 6.65265620e-11]
 [1.08907314e-02 9.78218537e-01 1.08907314e-02]
 [6.65265899e-11 3.32287099e-02 9.66771290e-01]]


In [13]:
# Rouwenhorst Method

def rouwen_method(RHO, SIGMA, N_GRID):
    p_rouwen = (1 + RHO) * 0.5
    q_rouwen = p_rouwen
    start_rouwen = -(((N_GRID - 1) / (1 - RHO**2)) ** 0.5) * SIGMA
    end_rouwen = -start_rouwen
    zgrid_rouwen = np.linspace(start_rouwen, end_rouwen, N_GRID)
    P_rouwen = np.append(
        [[p_rouwen, 1.0 - p_rouwen]], [[1 - q_rouwen, q_rouwen]], axis=0
    )

    for i in range(2, N_GRID):
        m1 = np.append(P_rouwen, np.zeros((i, 1)), axis=1)
        m1 = np.append(m1, np.zeros((1, i + 1)), axis=0)
        m2 = np.append(np.zeros((i, 1)), P_rouwen, axis=1)
        m2 = np.append(m2, np.zeros((1, i + 1)), axis=0)
        m3 = np.append(P_rouwen, np.zeros((i, 1)), axis=1)
        m3 = np.append(np.zeros((1, i + 1)), m3, axis=0)
        m4 = np.append(np.zeros((i, 1)), P_rouwen, axis=1)
        m4 = np.append(np.zeros((1, i + 1)), m4, axis=0)

        P_rouwen = (
            p_rouwen * m1 + (1 - p_rouwen) * m2 + (1 - q_rouwen) * m3 + q_rouwen * m4
        )
        P_rouwen[1:i, :] = 0.5 * P_rouwen[1:i, :]

    return P_rouwen, zgrid_rouwen

In [14]:
# Fix the parameters
RHO = 0.5
SIGMA = 0.1
N_GRID = 3
LAMBDA = 2.0

In [15]:
P_rouwen, zgrid_rouwen = rouwen_method(RHO, SIGMA, N_GRID)

In [16]:
print(P_rouwen)

[[0.5625 0.375  0.0625]
 [0.1875 0.625  0.1875]
 [0.0625 0.375  0.5625]]


In [17]:
print(zgrid_rouwen)

[-0.16329932  0.          0.16329932]


In [40]:
# Given transition matrix
p = np.array([[57, 24, 15],
              [10, 45, 78],
              [12, 37, 5]])

# Number of states
num_states = p.shape[0]

# Number of simulations
num_simulations = 10000

# Set the seed for reproducibility
np.random.seed(12345)

# Initialize the count matrix
count_matrix = np.zeros((num_states, num_states), dtype=int)

# Initialize process s_0, start at state 0
current_state = np.random.choice(num_states)

# Simulate the Markov Chain
for _ in range(num_simulations):
    next_state = np.random.choice(num_states, p=p[current_state])
    count_matrix[current_state, next_state] += 1
    current_state = next_state

# Print the count matrix
print("Transition count matrix:")
print(count_matrix)

# Optional: Normalize the count matrix to get the estimated transition matrix
Pest = (count_matrix.T / np.sum(count_matrix, axis=1)).T
print("Estimated transition matrix:")
print(Pest)




ValueError: probabilities do not sum to 1

In [25]:
# Stationary Disribution


P = np.array([
    [0.2, 0.8],
    [0.75, 0.25]
])


p_stat = 0.5 * np.ones((2))
for t in range(1, 100):
    p_stat = np.dot(P.T, p_stat)

print(p_stat)

[0.48387097 0.51612903]


In [39]:
import numpy as np
from scipy.stats import norm

# Given values
Xi_t_t_minus_1 = np.array([0.1, 0.9])
y_t = 1.5
mu = np.array([-3, 3])
P = np.array([[0.8, 0.2], [0.3, 0.7]])
#sigma = np.array([1, 1])  # Assuming standard deviation is 1 for this example

# Step 1: Compute predicted state probabilities
Xi_t_t_minus_1_pred = np.dot(P.T, Xi_t_t_minus_1)
print("Predicted state probabilities Xi_{t|t-1}:", Xi_t_t_minus_1_pred)

# Step 2: Calculate conditional densities
#f_t = norm.pdf(y_t, mu, sigma)

# Step 3: Calculate joint probabilities
#f_t_Xi_t_t_minus_1_pred = f_t * Xi_t_t_minus_1_pred

# Step 4: Calculate the unconditional density
#f_t_sum = np.sum(f_t_Xi_t_t_minus_1_pred)

# Step 5: Update state probabilities
#Xi_t_t = f_t_Xi_t_t_minus_1_pred / f_t_sum

# Step 6: Calculate optimal forecast for each state
#optimal_forecasts = mu

#print("Optimal forecasts for each state:", optimal_forecasts)
print("Updated state probabilities Xi_{t|t}:", Xi_t_t)

Predicted state probabilities Xi_{t|t-1}: [0.35 0.65]
Updated state probabilities Xi_{t|t}: [0.88079708 0.11920292]


In [38]:
import numpy as np
from numpy.random import seed, rand

# seed random number generator
seed(12345)
TARGET_PURSE = 12
INIT_PURSE = 3
N_STATES = TARGET_PURSE + 1
S = np.zeros((N_STATES, 1))
P = np.zeros((N_STATES, N_STATES))
P[0, 0] = 1.0
P[N_STATES - 1, N_STATES - 1] = 1.0
for ii in range(1, N_STATES - 1):
    for jj in range(0, N_STATES):
        if jj == ii - 1 or jj == ii + 1:
            P[ii, jj] = 0.5
print("Transition matrix:\n", P)

N_HISTORIES = 5000  # number of histories or simulations
LEN_HIST = 200  # Length of each simulation
histories = np.zeros((N_HISTORIES, LEN_HIST))
histories[:, 0] = INIT_PURSE * np.ones(N_HISTORIES)
randarray = rand(N_HISTORIES, LEN_HIST)
for i in range(0, N_HISTORIES):
    for j in range(1, LEN_HIST):
        histories[i, j] = (
            histories[i, j - 1] + (randarray[i, j] >= 0.5) - (randarray[i, j] < 0.5)
        )
        if histories[i, j] == TARGET_PURSE or histories[i, j] < 1:
            histories[i, j + 1 : LEN_HIST + 1] = histories[i, j]  # noQA E203
            break
target_num = np.sum(np.max(histories, axis=1) == TARGET_PURSE)
end_gamble = np.zeros(N_HISTORIES)
end_gamble_sum = 0
for i in range(0, N_HISTORIES):
    if np.max(histories[i, :]) == TARGET_PURSE:
        where_gamble_ends_T = np.where((histories[i, :] == TARGET_PURSE))
        end_gamble[i] = where_gamble_ends_T[0][0]
        end_gamble_sum += 1
    elif np.min(histories[i, :]) < 1:
        where_gamble_ends_0 = np.where((histories[i, :] < 1))
        end_gamble[i] = where_gamble_ends_0[0][0]
        end_gamble_sum += 1
    else:
        end_gamble[i] = 0.0
broke_num = np.sum(np.min(histories, axis=1) < 1)
print(
    "Probability of getting the target:",
    target_num / N_HISTORIES,
    "\nProbability of losing all the money:",
    broke_num / N_HISTORIES,
)
print(
    "Expected time until reaching a stopping result:",
    np.sum(end_gamble) / end_gamble_sum,
    "\nTotal number of simulations:",
    end_gamble_sum,
)

# Calculate expected steps to reach terminal state
Q = P[1:-1, 1:-1]  # Transition matrix for transient states
N = np.linalg.inv(np.eye(Q.shape[0]) - Q)
t = N.sum(axis=1)
expected_steps = t[INIT_PURSE - 1]  # -1 because Python uses 0-based indexing

print(f"Expected steps needed to reach the terminal state: {expected_steps}")

Transition matrix:
 [[1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.  0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.5]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. ]]
Probability of getting the target: 0.2468 
Probability of losing all the money: 0.7526
Expected time until reaching a stopping result: 27.09605763458075 
Total number of simulations: 4997
Expected steps needed to reach the terminal state: 27.0


In [55]:
import numpy as np

# Given transition count matrix
P_count = np.array([
    [57, 24, 15],
    [10, 45, 78],
    [12, 37, 5]
])

# Calculate row sums
row_sums = P_count.sum(axis=1)

# Normalize each row to get probabilities
P_estimated = P_count / row_sums[:, np.newaxis]

print("Estimated transition matrix:")
print(np.round(P_estimated, 4))

# Calculate the estimation error
total_transitions = P_count.sum()
estimation_error = 1 / np.sqrt(total_transitions)

print(f"\nEstimation error: {estimation_error:.4f}")

Estimated transition matrix:
[[0.5938 0.25   0.1562]
 [0.0752 0.3383 0.5865]
 [0.2222 0.6852 0.0926]]

Estimation error: 0.0594
